### ISSUE TITLE
clarify build/test instructions

### ISSUE THREAD

**Issue by ixje** [NeoResearch/csBigInteger.cpp#1]
I think the readme could use some extra words on what packages are needed for compiling as well as running the tests. For example; even though I already had a basic toolchain I still had to `apt-install libgtest-dev`. 

While having that installed I still couldn't run the tests. I navigate to the `/tests/` directory and run `make test` but still get greeted by error's due to `libgtest_main.a`, `libgtest.a` and `libgmock.a` not being found. 

I eventually to navigated to the individual folders `/tests/libgtest/googlemock/`, `/tests/libgtest/googletest/` and ran `cmake . && make` and then update the `Makefile` to point to the right build location (as I don't have a `/build/`) folder. I'm probably doing something wrong here, but it's not obvious what the correct steps are to building this project.

**Comment by igormcoelho** [comment]
Thats right,I'll create a 'make vendor' script,to configure tests library. And remember user regarding lgmp

**Comment by ixje** [comment]
👍

**Comment by igormcoelho** [comment]
Created a `Build Instructions` settings @ixje including a `make vendor` command.
You can do: `make vendor` and `make test`, directly on root folder now.
